//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEngineering.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int userID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
    }
}
